### ISSUE TITLE
snakemake

### ISSUE THREAD

**Issue by ibseq** [dorbarker/voc-identify#31]
Hello
how do you run multiple bam files using the voc-identify.smk?

thanks
ibseq

**Comment by dorbarker** [comment]
Hello ibseq,

I see you closed the issue. I presume you figured it out on your own, but in case you did not and for future users, I updated the readme to clarify use of the snakemake workflow. 

Hopefully the expanded readme is helpful for you and others.

Cheers,
Dillon
