### ISSUE TITLE
running multiple bam files 

### ISSUE THREAD

**Issue by ibseq** [dorbarker/voc-identify#33]
Hello
I tried to run the snakemake as below but I didn't get the outpust as expected. any advice? thanks :)

snakemake -c 1 -s /ibseq/MMMVI/voc-identify/voc-identify.smk -d reports/wwc019 --configfile example-config.yaml --jobs 2 
Creating specified working directory reports/wwc019.
Building DAG of jobs...
Using shell: /bin/bash
Provided cluster nodes: 2
Job counts:
        count   jobs
        1       all
        1
 
[Tue Jun 22 22:04:19 2021]
localrule all:
    jobid: 0
 
[Tue Jun 22 22:04:19 2021]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /ibseq/MMMVI/reports/wwc019/.snakemake/log/2021-06-22T220419.690500.snakemake.log

**Comment by dorbarker** [comment]
You would see this result if you ran snakemake in a project directory the (the `-d` flag) that doesn't match the directory structure given in the readme under the heading Automated Workflow
